import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const bahnschrift = localFont({
  src: "../../public/fonts/Bahnschrift.ttf",
  variable: "--font-bahnschrift",
})

export const metadata: Metadata = {
  title: "Sad Girl Sessions",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${bahnschrift.variable} bg-black font-sans text-white`}>
        {children}
      </body>
    </html>
  )
}
